### ISSUE TITLE
how to compare time for current prayer time and next prayer time please tell me

### ISSUE THREAD

**Issue by aneebali** [ahmedeltaher/Azan#11]

**Comment by Itay80600** [comment]
How did you do it eventually? @aneebali

**Comment by ahmedeltaher** [comment]
Please here is the issue tracker, not for questions and answers.
This is not a bug issue. 
However, I don't get your question, could you please clarify more? 
By the way, you have a list of time-prayers for the date you provided, if your question is how to compare two time/dates objects then you can find a lot of ways to do that
