### ISSUE TITLE
Prayer time not correct

### ISSUE THREAD

**Issue by AmitPal100001** [ahmedeltaher/Azan#12]
Hello sir,

I am not getting exactly time for prayer for my country India. can you describe me how can I get exactly prayer time?

I am waiting your response.

Thanks,
Amit Pal

**Comment by bassam514748** [comment]
it is not correct i agreed, how to solve

**Comment by MohammadNouri5700** [comment]
HI 
THIS IS NOT CORRECT RESPONSE

**Comment by AmitPal100001** [comment]
Ok

**Comment by ahmedeltaher** [comment]
@AmitPal100001 @bassam514748 , according to which configuration you use the lib and the according to what you compare, could you please clarify. 
it might be you use a different calculation type and angle then you expect the returned time have to match another result. 
could you provide us with a use case to fix it, if it is a bug
