### ISSUE TITLE
Doesnt give proper value for different timezones

### ISSUE THREAD

**Issue by imranctg16** [ahmedeltaher/Azan#5]
The value returned for +6 timezone was way off to the original value.

I passed the timezone parameter as double (6.0) but it gave me wrong output . 
Then i tried putting some manual lat and long with their timezone,, value didnt match,
Please fix the timezone calculation. otherwise its a great library !

**Comment by ahmedeltaher** [comment]
did you check the calculation method when you compared the result? 
please give me an example with full inputs and the expected results
