### ISSUE TITLE
Allow to set a custom AngleCalculationType

### ISSUE THREAD

**Issue by sayah-y** [ahmedeltaher/Azan#9]
Hello,

Thanks for your work !

I want to use your library for my project but I cannot. Because I want to set a custom AngleCalculationType and not pre-defined values "MWL(18, 17), ISNA(15, 15), EGYPT(19.5, 17.5), KARACHI(18, 18), MUHAMMADIYAH(20, 18)".

Can I do this ?

Thanks.

**Comment by sayah-y** [comment]
I just see the new version. The readme is not updated. Thanks for your work.

**Comment by sayah-y** [comment]
I use the version 2.2 and I don't see all AngleCalculationType. For example, I don't see UOIF (Union des organisations islamiques de France).

Thanks.

**Comment by ahmedeltaher** [comment]
what you posted it is not a bug.
by the way, you can find UOIF(12, 12) in the enum.
There is no feature for adding custom AngleCalculationType.
